spring:
  config:
    activate:
      on-profile: dev
    import:
      - file:dev.env[.properties]

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: ${MYSQL_URL}
  #    username: ${MYSQL_USERNAME}
  #    password: ${MYSQL_PASSWORD}

  sql:
    init:
      platform: h2
  #      platform: mysql

  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
#      hibernate.use_sql_comments: true

#      h2:
#        console:
#          enabled: true
#          path: /h2-console
jwt:
  issuer: localhost
vapid:
  public:
    key: ${VAPID_PUBLIC_KEY}
  private:
    key: ${VAPID_PRIVATE_KEY}