spring:
  config:
    activate:
      on-profile: dev
    import:
      - file:dev.env[.properties]

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      platform: h2

  jpa:
    hibernate:
      ddl-auto: create

server:
  port: ${SERVER_PORT}
blockchain:
  min-gas-price: ${MIN_GAS_PRICE}
  max-gas-price: ${MAX_GAS_PRICE}
  system-private-key: ${BLOCKCHAIN_PRIVATE_KEY}
  system-wallet-address: ${BLOCKCHAIN_WALLET_ADDRESS}
  rpc-url: ${BLOCKCHAIN_RPC_URL}
  contract-addresses:
    melodiket: ${MELODIKET_CONTRACT_ADDRESS}
    melody-token: ${MELODY_TOKEN_CONTRACT_ADDRESS}
security:
  allowed-origins: "${SECURITY_ALLOWED_ORIGINS}"
jwt:
  issuer: localhost
