spring:
  config:
    activate:
      on-profile: dev
    import:
      - file:dev.env[.properties]
server:
  port: ${SERVER_PORT}
blockchain:
  gas-price: ${GAS_PRICE}
  gas-limit: ${GAS_LIMIT}
  system-private-key: ${BLOCKCHAIN_PRIVATE_KEY}
  system-wallet-address: ${BLOCKCHAIN_WALLET_ADDRESS}
  rpc-url: ${BLOCKCHAIN_RPC_URL}
  contract-addresses:
    melodiket: ${MELODIKET_CONTRACT_ADDRESS}
    melody-token: ${MELODY_TOKEN_CONTRACT_ADDRESS}
    ticket: ${TICKET_CONTRACT_ADDRESS}
