spring:
  application:
    name: melodiket
  config:
    import:
      - classpath:/yaml/application-dev.yml
      - classpath:/yaml/application-release.yml
      - file:.env[.properties]

  profiles:
    group:
      dev: dev
      release: release
    active: ${CURRENT_ENV}

jwt:
  secret: ${JWT_SECRET}

