spring:
  application:
    name: melodiket
  config:
    import:
      - classpath:/yaml/application-dev.yml
      - classpath:/yaml/application-release.yml
      - file:.env[.properties]

  profiles:
    group:
      dev: dev
      release: release
    active: ${CURRENT_ENV}

server:
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_SECRET}
security:
  allowed-origins: ${SECURITY_ALLOWED_ORIGINS}

blockchain:
  gas-price: ${GAS_PRICE}
  gas-limit: ${GAS_LIMIT}
  system-private-key: ${BLOCKCHAIN_PRIVATE_KEY}
  system-wallet-address: ${BLOCKCHAIN_WALLET_ADDRESS}
  rpc-url: ${BLOCKCHAIN_RPC_URL}
  contract-addresses:
    melodiket: ${MELODIKET_CONTRACT_ADDRESS}
    melody-token: ${MELODY_TOKEN_CONTRACT_ADDRESS}
    ticket: ${TICKET_CONTRACT_ADDRESS}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET_NAME}
      presigned-url-expired: ${PRESIGNED_EXPIRE_TIME}
cloudfront:
  domain: ${CLOUDFRONT_DOMAIN}

redis:
  url: ${REDIS_URL}

bank:
  api-endpoint: ${BANK_SERVER_URL}
  owner:
    name: 멜로디켓
    yymmdd: "000000"